AWSTemplateFormatVersion: 2010-09-09


Parameters:
  Cluster:
    Type: String

  VpcId:
    Type: AWS::EC2::VPC::Id

  TaskExecutionRole:
    Type: String

  LogGroup:
    Type: String

  PrivateNamespace:
    Type: String

  MongoDbPassword:
    Type: String

Resources:
  MongoDbService:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref Cluster
      DesiredCount: 1
      TaskDefinition: !Ref MongoDbTaskDefinition
      LaunchType: EC2
      ServiceRegistries:
        - RegistryArn: !GetAtt MongoDbDiscoveryService.Arn
          ContainerName: mongodb-container
          ContainerPort: 27017

  MongoDbTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: mongodb
      RequiresCompatibilities:
        - EC2
      Memory: 512
      Cpu: 512
      NetworkMode: bridge
      ExecutionRoleArn: !Ref TaskExecutionRole
      ContainerDefinitions:
        - Name: mongodb-container
          Image: mongo:latest
          Essential: true
          PortMappings:
            - Protocol: tcp
              ContainerPort: 27017
          MountPoints:
            - SourceVolume: mongodb-data
              ContainerPath: /data/db
              ReadOnly: false
          Environment:
            - Name: MONGO_INITDB_ROOT_PASSWORD
              Value: !Ref MongoDbPassword
            - Name: MONGO_INITDB_ROOT_USERNAME
              Value: admin
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-region: !Ref AWS::Region
              awslogs-group: !Ref LogGroup
              awslogs-stream-prefix: !Sub /ecs/${AWS::StackName}/mongodb
      Volumes:
        - Name: mongodb-data
          DockerVolumeConfiguration:
            Scope: shared
            AutoProvision: true
            Driver: rexray/ebs
            DriverOpts:
              volumetype: gp2
              size: 10


  MongoDbDiscoveryService:
    Type: AWS::ServiceDiscovery::Service
    Properties:
      DnsConfig:
        RoutingPolicy: MULTIVALUE
        DnsRecords:
          - TTL: 60
            Type: SRV
      HealthCheckCustomConfig:
        FailureThreshold: 1
      Name: _mongodb._tcp.mongodb
      NamespaceId: !Ref PrivateNamespace

Outputs:
  RedisService:
    Value: !Ref MongoDbService

