AWSTemplateFormatVersion: '2010-09-09'
Description: >
  CloudFormation stack for development and test environment on AWS ECS.
  It meant to be edge, unstable, non-persistent.
  This environment will not have fixed URL.

Parameters:
  InstanceType:
    Type: String
    Default: t3.small

  MaintenanceIpRange:
    Type: String

  MongoDbPassword:
    Type: String

  PublicHostname:
    Type: String

  AppImage:
    Type: String

  AppTaskCount:
    Type: String
    Default: 3

  CertificateArn:
    Type: String

  GoogleAnalyticsId:
    Type: String

  UploadedImageStore:
    Type: String
    Default: local

  AwsKey:
    Type: String
    Default: NOT_SET

  AwsSecret:
    Type: String
    Default: NOT_SET

  DebugOpts:
    Type: String
    Default: NOT_SET

Resources:
  VPC:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: templates/vpc.yaml

  Cluster:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: templates/cluster.yaml
      Parameters:
        InstanceType: !Ref InstanceType
        VpcId: !GetAtt VPC.Outputs.VpcId
        Subnets: !GetAtt VPC.Outputs.Subnets
        LBSecurityGroup: !GetAtt LoadBalancer.Outputs.LBSecurityGroup
        MaintenanceIpRange: !Ref MaintenanceIpRange

  LoadBalancer:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: templates/load-balancer.yaml
      Parameters:
        PublicHostname: !Ref PublicHostname
        Subnets: !GetAtt VPC.Outputs.Subnets
        VpcId: !GetAtt VPC.Outputs.VpcId
        CertificateArn: !Ref CertificateArn

  Service:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: templates/service.yaml
      Parameters:
        VpcId: !GetAtt VPC.Outputs.VpcId
        Cluster: !GetAtt Cluster.Outputs.ClusterName
        LoadBalancerListener: !GetAtt LoadBalancer.Outputs.LoadBalancerListener
        TargetGroup: !GetAtt LoadBalancer.Outputs.TargetGroup
        MongoDbPassword: !Ref MongoDbPassword
        AppImage: !Ref AppImage
        AppTaskCount: !Ref AppTaskCount
        PublicHostname: !Ref PublicHostname
        GoogleAnalyticsId: !Ref GoogleAnalyticsId
        AwsKey: !Ref AwsKey
        AwsSecret: !Ref AwsSecret
        UploadedImageStore: !Ref UploadedImageStore
        ImageBucket: !GetAtt S3Bucket.Outputs.ImageBucket
        DebugOpts: !Ref DebugOpts

  S3Bucket:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: templates/s3-bucket.yaml
