AWSTemplateFormatVersion: '2010-09-09'
Description: >
  CloudFormation stack for development and test environment on AWS ECS.
  It meant to be edge, unstable, non-persistent.
  This environment will not have fixed URL.

Parameters:
  MaintenanceIpRange:
    Type: String

  MongoDbPassword:
    Type: String

  AppImage:
    Type: String

Resources:
  VPC:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: templates/vpc.yaml

  Cluster:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: templates/cluster.yaml
      Parameters:
        VpcId: !GetAtt VPC.Outputs.VpcId
        Subnets: !GetAtt VPC.Outputs.Subnets
        LBSecurityGroup: !GetAtt LoadBalancer.Outputs.LBSecurityGroup
        MaintenanceIpRange: !Ref MaintenanceIpRange

  LoadBalancer:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: templates/load-balancer.yaml
      Parameters:
        Subnets: !GetAtt VPC.Outputs.Subnets
        VpcId: !GetAtt VPC.Outputs.VpcId

  Service:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: templates/service.yaml
      Parameters:
#        Subnets: !GetAtt VPC.Outputs.Subnets
        VpcId: !GetAtt VPC.Outputs.VpcId
        Cluster: !GetAtt Cluster.Outputs.ClusterName
        LoadBalancerListener: !GetAtt LoadBalancer.Outputs.LoadBalancerListener
        TargetGroup: !GetAtt LoadBalancer.Outputs.TargetGroup
        MongoDbPassword: !Ref MongoDbPassword
        AppImage: !Ref AppImage




