AWSTemplateFormatVersion: '2010-09-09'
Description: >
  CloudFormation stack for development and test environment on AWS ECS.
  It meant to be edge, unstable, non-persistent.
  This environment will not have fixed URL.

Resources:
  VPC:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: templates/vpc.yaml

