AWSTemplateFormatVersion: 2010-09-09


Parameters:
  Cluster:
    Type: String

  LoadBalancerListener:
    Type: String

  TargetGroup:
    Type: String

#  SourceSecurityGroup:
#    Type: AWS::EC2::SecurityGroup::Id

#  Subnets:
#    Type: List<AWS::EC2::Subnet::Id>

  VpcId:
    Type: AWS::EC2::VPC::Id

  MongoDbPassword:
    Type: String

  AppImage:
    Type: String

  AppTaskCount:
    Type: String

  PublicHostname:
    Type: String

  GoogleAnalyticsId:
    Type: String

  UploadedImageStore:
    Type: String

  AwsKey:
    Type: String

  AwsSecret:
    Type: String

  ImageBucket:
    Type: String

  FlaskEnv:
    Type: String

  DebugOpts:
    Type: String

Resources:
  TaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy

  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /ecs/${AWS::StackName}

  PrivateNamespace:
    Type: AWS::ServiceDiscovery::PrivateDnsNamespace
    Properties:
      Name: asobann-internal.yattom.jp.
      Vpc: !Ref VpcId

  RedisService:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: service/redis.yaml
      Parameters:
        VpcId: !Ref VpcId
        Cluster: !Ref Cluster
        TaskExecutionRole: !Ref TaskExecutionRole
        LogGroup: !Ref LogGroup
        PrivateNamespace: !Ref PrivateNamespace

  MongoDbService:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: service/mongodb.yaml
      Parameters:
        VpcId: !Ref VpcId
        Cluster: !Ref Cluster
        TaskExecutionRole: !Ref TaskExecutionRole
        LogGroup: !Ref LogGroup
        PrivateNamespace: !Ref PrivateNamespace
        MongoDbPassword: !Ref MongoDbPassword

  AppService:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: service/app.yaml
      Parameters:
        VpcId: !Ref VpcId
        Cluster: !Ref Cluster
        TaskExecutionRole: !Ref TaskExecutionRole
        LogGroup: !Ref LogGroup
        LoadBalancerListener: !Ref LoadBalancerListener
        TargetGroup: !Ref TargetGroup
        MongoDbPassword: !Ref MongoDbPassword
        AppImage: !Ref AppImage
        AppTaskCount: !Ref AppTaskCount
        PublicHostname: !Ref PublicHostname
        GoogleAnalyticsId: !Ref GoogleAnalyticsId
        UploadedImageStore: !Ref UploadedImageStore
        AwsKey: !Ref AwsKey
        AwsSecret: !Ref AwsSecret
        ImageBucket: !Ref ImageBucket
        FlaskEnv: !Ref FlaskEnv
        DebugOpts: !Ref DebugOpts

Outputs:
  RedisService:
    Value: !Ref RedisService

