AWSTemplateFormatVersion: 2010-09-09


Parameters:
  Cluster:
    Type: String

  TargetGroup:
    Type: String

#  SourceSecurityGroup:
#    Type: AWS::EC2::SecurityGroup::Id

#  Subnets:
#    Type: List<AWS::EC2::Subnet::Id>

  VpcId:
    Type: AWS::EC2::VPC::Id

Resources:
  TaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy

  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /ecs/${AWS::StackName}

  #  PrivateHostedZone:
  #    Type: AWS::Route53::HostedZone
  #    Properties:
  #      Name: asobann-dev.
  #      VPCs:
  #        - !GetAtt VPC.Outputs.VpcId

  PrivateNamespace:
    Type: AWS::ServiceDiscovery::PrivateDnsNamespace
    Properties:
      Name: asobann-dev.
      Vpc: !Ref VpcId

  RedisService:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: service/redis.yaml
      Parameters:
        VpcId: !Ref VpcId
        Cluster: !Ref Cluster
        TaskExecutionRole: !Ref TaskExecutionRole
        LogGroup: !Ref LogGroup
        PrivateNamespace: !Ref PrivateNamespace

  MongoDbDiscoveryService:
    Type: AWS::ServiceDiscovery::Service
    Properties:
      DnsConfig:
        RoutingPolicy: MULTIVALUE
        DnsRecords:
          - TTL: 60
            Type: SRV
      HealthCheckCustomConfig:
        FailureThreshold: 1
      Name: mongodb
      NamespaceId: !Ref PrivateNamespace

Outputs:
  RedisService:
    Value: !Ref RedisService

